//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DF_WebModule.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Engineering_DBEntities : DbContext
    {
        public Engineering_DBEntities()
            : base("name=Engineering_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ConfigSetting> ConfigSettings { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DublicateSRNumber> DublicateSRNumbers { get; set; }
        public virtual DbSet<Master_Role> Master_Role { get; set; }
        public virtual DbSet<PartDetail> PartDetails { get; set; }
        public virtual DbSet<PartQRCount> PartQRCounts { get; set; }
        public virtual DbSet<PrintandScanQRData> PrintandScanQRDatas { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
    }
}
