//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DF_WebModule.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DublicateSRNumber
    {
        public long Id { get; set; }
        public string PartNo { get; set; }
        public int Count { get; set; }
        public int StartSRNo { get; set; }
        public System.DateTime Date { get; set; }
        public int Status { get; set; }
        public string Customer { get; set; }
        public string RevNo { get; set; }
    }
}
