//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DF_WebModule.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartDetail
    {
        public long Id { get; set; }
        public string PartNumber { get; set; }
        public string Part_Description { get; set; }
        public string Joint { get; set; }
        public string Tube_Length { get; set; }
        public string TypeOfPart { get; set; }
        public string CustomerName { get; set; }
        public string VendorCode { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string Remark { get; set; }
        public string RevNo { get; set; }
    }
}
