//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DF_WebModule.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrintandScanQRData
    {
        public long Id { get; set; }
        public string PartNumber { get; set; }
        public string QrText { get; set; }
        public bool IsScaned { get; set; }
        public System.DateTime PrintingTime { get; set; }
        public Nullable<System.DateTime> ScaningTime { get; set; }
    }
}
