//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DF_WebModule.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public long Id { get; set; }
        public long RoleId { get; set; }
        public string Name { get; set; }
        public string MobileNo { get; set; }
        public string Email_Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifyedOn { get; set; }
    
        public virtual Master_Role Master_Role { get; set; }
    }
}
