//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DF_WebModule.SymlLicenseService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SymlLicenseServiceSoap", Namespace="http://symlconnect.com/")]
    public partial class SymlLicenseService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateSessionOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckSessionOperationCompleted;
        
        private System.Threading.SendOrPostCallback CloseSessionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateActivationOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertLicenseOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckLicenseOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SymlLicenseService() {
            this.Url = global::DF_WebModule.Properties.Settings.Default.DF_WebModule_SymlLicenseService_SymlLicenseService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateSessionCompletedEventHandler CreateSessionCompleted;
        
        /// <remarks/>
        public event CheckSessionCompletedEventHandler CheckSessionCompleted;
        
        /// <remarks/>
        public event CloseSessionCompletedEventHandler CloseSessionCompleted;
        
        /// <remarks/>
        public event ValidateActivationCompletedEventHandler ValidateActivationCompleted;
        
        /// <remarks/>
        public event InsertLicenseCompletedEventHandler InsertLicenseCompleted;
        
        /// <remarks/>
        public event CheckLicenseCompletedEventHandler CheckLicenseCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://symlconnect.com/CreateSession", RequestNamespace="http://symlconnect.com/", ResponseNamespace="http://symlconnect.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateSession(string SessionKey, string Token) {
            object[] results = this.Invoke("CreateSession", new object[] {
                        SessionKey,
                        Token});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateSessionAsync(string SessionKey, string Token) {
            this.CreateSessionAsync(SessionKey, Token, null);
        }
        
        /// <remarks/>
        public void CreateSessionAsync(string SessionKey, string Token, object userState) {
            if ((this.CreateSessionOperationCompleted == null)) {
                this.CreateSessionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateSessionOperationCompleted);
            }
            this.InvokeAsync("CreateSession", new object[] {
                        SessionKey,
                        Token}, this.CreateSessionOperationCompleted, userState);
        }
        
        private void OnCreateSessionOperationCompleted(object arg) {
            if ((this.CreateSessionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateSessionCompleted(this, new CreateSessionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://symlconnect.com/CheckSession", RequestNamespace="http://symlconnect.com/", ResponseNamespace="http://symlconnect.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckSession(string SessionID) {
            object[] results = this.Invoke("CheckSession", new object[] {
                        SessionID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckSessionAsync(string SessionID) {
            this.CheckSessionAsync(SessionID, null);
        }
        
        /// <remarks/>
        public void CheckSessionAsync(string SessionID, object userState) {
            if ((this.CheckSessionOperationCompleted == null)) {
                this.CheckSessionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckSessionOperationCompleted);
            }
            this.InvokeAsync("CheckSession", new object[] {
                        SessionID}, this.CheckSessionOperationCompleted, userState);
        }
        
        private void OnCheckSessionOperationCompleted(object arg) {
            if ((this.CheckSessionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckSessionCompleted(this, new CheckSessionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://symlconnect.com/CloseSession", RequestNamespace="http://symlconnect.com/", ResponseNamespace="http://symlconnect.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CloseSession(string SessionID) {
            object[] results = this.Invoke("CloseSession", new object[] {
                        SessionID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CloseSessionAsync(string SessionID) {
            this.CloseSessionAsync(SessionID, null);
        }
        
        /// <remarks/>
        public void CloseSessionAsync(string SessionID, object userState) {
            if ((this.CloseSessionOperationCompleted == null)) {
                this.CloseSessionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCloseSessionOperationCompleted);
            }
            this.InvokeAsync("CloseSession", new object[] {
                        SessionID}, this.CloseSessionOperationCompleted, userState);
        }
        
        private void OnCloseSessionOperationCompleted(object arg) {
            if ((this.CloseSessionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CloseSessionCompleted(this, new CloseSessionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://symlconnect.com/ValidateActivation", RequestNamespace="http://symlconnect.com/", ResponseNamespace="http://symlconnect.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ValidateActivation(string SessionID, string ActivationKey, string Organisation, string Identity, string Region, out string ActivationToken) {
            object[] results = this.Invoke("ValidateActivation", new object[] {
                        SessionID,
                        ActivationKey,
                        Organisation,
                        Identity,
                        Region});
            ActivationToken = ((string)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateActivationAsync(string SessionID, string ActivationKey, string Organisation, string Identity, string Region) {
            this.ValidateActivationAsync(SessionID, ActivationKey, Organisation, Identity, Region, null);
        }
        
        /// <remarks/>
        public void ValidateActivationAsync(string SessionID, string ActivationKey, string Organisation, string Identity, string Region, object userState) {
            if ((this.ValidateActivationOperationCompleted == null)) {
                this.ValidateActivationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateActivationOperationCompleted);
            }
            this.InvokeAsync("ValidateActivation", new object[] {
                        SessionID,
                        ActivationKey,
                        Organisation,
                        Identity,
                        Region}, this.ValidateActivationOperationCompleted, userState);
        }
        
        private void OnValidateActivationOperationCompleted(object arg) {
            if ((this.ValidateActivationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateActivationCompleted(this, new ValidateActivationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://symlconnect.com/InsertLicense", RequestNamespace="http://symlconnect.com/", ResponseNamespace="http://symlconnect.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertLicense(string SessionID, string LicenseKey, string Organisation, string Identity, string Region, string Months, string Product) {
            object[] results = this.Invoke("InsertLicense", new object[] {
                        SessionID,
                        LicenseKey,
                        Organisation,
                        Identity,
                        Region,
                        Months,
                        Product});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertLicenseAsync(string SessionID, string LicenseKey, string Organisation, string Identity, string Region, string Months, string Product) {
            this.InsertLicenseAsync(SessionID, LicenseKey, Organisation, Identity, Region, Months, Product, null);
        }
        
        /// <remarks/>
        public void InsertLicenseAsync(string SessionID, string LicenseKey, string Organisation, string Identity, string Region, string Months, string Product, object userState) {
            if ((this.InsertLicenseOperationCompleted == null)) {
                this.InsertLicenseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertLicenseOperationCompleted);
            }
            this.InvokeAsync("InsertLicense", new object[] {
                        SessionID,
                        LicenseKey,
                        Organisation,
                        Identity,
                        Region,
                        Months,
                        Product}, this.InsertLicenseOperationCompleted, userState);
        }
        
        private void OnInsertLicenseOperationCompleted(object arg) {
            if ((this.InsertLicenseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertLicenseCompleted(this, new InsertLicenseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://symlconnect.com/CheckLicense", RequestNamespace="http://symlconnect.com/", ResponseNamespace="http://symlconnect.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckLicense(string SessionID, string LicenseKey, string Identity, string dateAct, string Product, out System.DateTime dateExp) {
            object[] results = this.Invoke("CheckLicense", new object[] {
                        SessionID,
                        LicenseKey,
                        Identity,
                        dateAct,
                        Product});
            dateExp = ((System.DateTime)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckLicenseAsync(string SessionID, string LicenseKey, string Identity, string dateAct, string Product) {
            this.CheckLicenseAsync(SessionID, LicenseKey, Identity, dateAct, Product, null);
        }
        
        /// <remarks/>
        public void CheckLicenseAsync(string SessionID, string LicenseKey, string Identity, string dateAct, string Product, object userState) {
            if ((this.CheckLicenseOperationCompleted == null)) {
                this.CheckLicenseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckLicenseOperationCompleted);
            }
            this.InvokeAsync("CheckLicense", new object[] {
                        SessionID,
                        LicenseKey,
                        Identity,
                        dateAct,
                        Product}, this.CheckLicenseOperationCompleted, userState);
        }
        
        private void OnCheckLicenseOperationCompleted(object arg) {
            if ((this.CheckLicenseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckLicenseCompleted(this, new CheckLicenseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CreateSessionCompletedEventHandler(object sender, CreateSessionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateSessionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateSessionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CheckSessionCompletedEventHandler(object sender, CheckSessionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckSessionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckSessionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CloseSessionCompletedEventHandler(object sender, CloseSessionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CloseSessionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CloseSessionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ValidateActivationCompletedEventHandler(object sender, ValidateActivationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateActivationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateActivationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string ActivationToken {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void InsertLicenseCompletedEventHandler(object sender, InsertLicenseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertLicenseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertLicenseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CheckLicenseCompletedEventHandler(object sender, CheckLicenseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckLicenseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckLicenseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.DateTime dateExp {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591